@extends('layouts.admin')
@section('title', 'Data Wisata')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3 mb-0">Data Wisata</h1><a class="btn btn-primary" href="{{ route('admin.wisata.create') }}">Tambah Wisata</a></div>
<form class="row g-2 mb-3"><div class="col-lg-4"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Cari nama, jenis, atau alamat"></div><div class="col-lg-3"><select class="form-select" name="kategori"><option value="">Semua kategori</option>@foreach ($kategori as $item)<option value="{{ $item->id }}" @selected(request('kategori') == $item->id)>{{ $item->nama_kategori }}</option>@endforeach</select></div><div class="col-lg-2"><select class="form-select" name="status"><option value="">Semua status</option><option value="aktif" @selected(request('status') === 'aktif')>Aktif</option><option value="nonaktif" @selected(request('status') === 'nonaktif')>Nonaktif</option></select></div><div class="col-auto"><button class="btn btn-outline-primary">Filter</button> <a class="btn btn-light" href="{{ route('admin.wisata.index') }}">Reset</a></div></form>
<div class="card shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Foto</th><th>Wisata</th><th>Kategori/Jenis</th><th>Alamat</th><th>Estimasi</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>
@forelse ($wisata as $item)<tr><td>@if($item->foto_url)<img class="thumb rounded" src="{{ $item->foto_url }}" alt="{{ $item->nama_wisata }}" loading="lazy">@else<span class="d-inline-flex align-items-center justify-content-center bg-light text-muted rounded" style="width:86px;height:62px"><i class="bi bi-image"></i></span>@endif</td><td class="fw-semibold">{{ $item->nama_wisata }}</td><td>{{ $item->kategoriWisata->nama_kategori }}<br><small class="text-muted">{{ $item->jenis_wisata }}</small></td><td>{{ Str::limit($item->alamat, 55) }}</td><td>Rp {{ number_format($item->total_estimasi_biaya, 0, ',', '.') }}</td><td><span class="badge text-bg-{{ $item->status === 'aktif' ? 'success' : 'secondary' }}">{{ ucfirst($item->status) }}</span></td><td class="text-end text-nowrap"><a class="btn btn-sm btn-outline-info" href="{{ route('admin.wisata.show', $item) }}">Detail</a> <a class="btn btn-sm btn-outline-primary" href="{{ route('admin.wisata.edit', $item) }}">Edit</a> <form class="d-inline" method="POST" action="{{ route('admin.wisata.destroy', $item) }}" onsubmit="return confirm('Hapus sementara destinasi ini?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Hapus</button></form></td></tr>
@empty<tr><td colspan="7" class="text-center text-muted py-4">Data wisata tidak ditemukan.</td></tr>@endforelse
</tbody></table></div></div><div class="mt-3">{{ $wisata->links() }}</div>
@endsection
